version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ecommerce_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app   # So changes reflect without rebuild
    environment:
      FLASK_ENV: development

  frontend:
    build: ./frontend
    container_name: ecommerce_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
